version: '3.3'

services:
  data_protection_web:
    build: .
    ports:
      - 5000:5000
    links:
      - data_protection_db
    environment:
      TZ: 'America/Sao_Paulo'
      PYTHONUNBUFFERED: 1
    volumes:
      - ./data:/flask-app/data

  data_protection_db:
    image: postgres:14.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: data_protection
      TZ: 'America/Sao_Paulo'
      PGTZ: 'America/Sao_Paulo'
    ports:
      - '5433:5432'
    volumes:
      - data_protection_database:/var/lib/postgresql/data/

volumes:
  data_protection_database: