version: '3.8'

services:
  data_protection_web:
    build: .
    ports:
      - 5000:5000
    links:
      - data_protection_db
    environment:
      TZ: 'America/Sao_Paulo'
    depends_on:
      data_protection_db:
        condition: service_healthy

  data_protection_db:
    image: postgres:14.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: data_protection
      TZ: 'America/Sao_Paulo'
      PGTZ: 'America/Sao_Paulo'
    ports:
      - '5433:5432'
    volumes:
      - data_protection_database:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  data_protection_database:


networks:
  default:
    name: data_protection_network
